name: Javadoc Test Build

# Run this only on PRs into main so team's know that Javadoc publish won't fail
# Don't want to waste gh runner minutes either.
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_publish_jdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout repo to remote machine
      - name: Set up OpenJDK21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build Javadoc
        run: |
          cd $GRADLE_DIR
          chmod +x ./gradlew
          ./gradlew javadoc
        env:
          GRADLE_DIR: 'source' # Modify this to wherever './gradlew' is
