name: SonarCloud Check

on:
  pull_request:
    branches:
      - main

jobs:
  build_game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repo to remote machine
      - name: Set up OpenJDK21 # Need to change to JDK21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      # SonarCloud Integration
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and Analyse Game
        run: |
          cd $GRADLE_DIR
          chmod +x ./gradlew
          ./gradlew sonarqube --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GRADLE_DIR: 'source' # Modify this to wherever './gradlew' is